#!/bin/bash

GROWL_COMMAND=/usr/local/bin/growlnotify
NOTIFIER_COMMAND=/usr/local/bin/terminal-notifier
message="${1:-Done}"
title="${2:-Local command}"

if [ -e "$NOTIFIER_COMMAND" ]; then
    $NOTIFIER_COMMAND -message "$message" -title "$title" -sound Submarine
    exit 0
fi

if [ -e "$GROWL_COMMAND" ]; then
    $GROWL_COMMAND -m "$message" -t "$title"
    exit 0
fi


title="${2:-Remote command}"
ssh back '~/.bin/nb' "'$message'" "'$title'"


